sudo: false

language: node_js

matrix:
  include:
    - node_js: 'node'
      env: NPM_RUN_SCRIPT=test
    - node_js: '10'
    - node_js: '9'
    - node_js: '8'
    - node_js: '7'
    - node_js: '6'
    - node_js: '5'
    - node_js: '4'
      env: NODE_ENV=production
    - node_js: 'iojs-v3.3'
      env: NODE_ENV=production
    - node_js: 'iojs-v2.5'
      env: NODE_ENV=production
    - node_js: 'iojs-v1.8'
      env: NODE_ENV=production
    - node_js: '0.12'
      env: NODE_ENV=production
    - node_js: '0.10'
      env: NODE_ENV=production

install:
  - npm install

script:
  - npm run ${NPM_RUN_SCRIPT:-test:spec}
