sudo: false

language: node_js

matrix:
  include:
    - node_js: "10"
      env: NPM_RUN_SCRIPT=test
    - node_js: "9"
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"
    - node_js: "5"
    - node_js: "4"
    - node_js: "iojs-v3.3"
    - node_js: "iojs-v2.5"
    - node_js: "iojs-v1.8"
    - node_js: "0.12"
    - node_js: "0.10"

install:
  - npm install

script:
  - npm run ${NPM_RUN_SCRIPT:-test:api}
